# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.centerBeam_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.centerBeam_pushButton.setObjectName("centerBeam_pushButton")
        self.gridLayout_3.addWidget(self.centerBeam_pushButton, 0, 0, 1, 1)
        self.centerBeamSingle_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.centerBeamSingle_pushButton.setObjectName("centerBeamSingle_pushButton")
        self.gridLayout_3.addWidget(self.centerBeamSingle_pushButton, 1, 0, 1, 1)
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.gridLayout_3.addWidget(self.stop_pushButton, 3, 0, 1, 1)
        self.eraseLearned_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.eraseLearned_pushButton.setObjectName("eraseLearned_pushButton")
        self.gridLayout_3.addWidget(self.eraseLearned_pushButton, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.apply_filter_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.apply_filter_checkBox.setObjectName("apply_filter_checkBox")
        self.gridLayout_5.addWidget(self.apply_filter_checkBox, 0, 0, 1, 2)
        self.filter_mode_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filter_mode_comboBox.setObjectName("filter_mode_comboBox")
        self.filter_mode_comboBox.addItem("")
        self.filter_mode_comboBox.addItem("")
        self.filter_mode_comboBox.addItem("")
        self.filter_mode_comboBox.addItem("")
        self.filter_mode_comboBox.addItem("")
        self.filter_mode_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.filter_mode_comboBox, 1, 0, 1, 2)
        self.show_mask_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.show_mask_checkBox.setEnabled(False)
        self.show_mask_checkBox.setObjectName("show_mask_checkBox")
        self.gridLayout_5.addWidget(self.show_mask_checkBox, 2, 0, 1, 2)
        self.get_centroid_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.get_centroid_checkBox.setObjectName("get_centroid_checkBox")
        self.gridLayout_5.addWidget(self.get_centroid_checkBox, 3, 0, 1, 2)
        self.centroid_x_label = QtWidgets.QLabel(self.centralwidget)
        self.centroid_x_label.setObjectName("centroid_x_label")
        self.gridLayout_5.addWidget(self.centroid_x_label, 4, 0, 1, 1)
        self.centroid_y_label = QtWidgets.QLabel(self.centralwidget)
        self.centroid_y_label.setObjectName("centroid_y_label")
        self.gridLayout_5.addWidget(self.centroid_y_label, 5, 0, 1, 1)
        self.save_centroid_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.save_centroid_checkBox.setEnabled(False)
        self.save_centroid_checkBox.setObjectName("save_centroid_checkBox")
        self.gridLayout_5.addWidget(self.save_centroid_checkBox, 6, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 9, 1, 1, 1)
        self.filename_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filename_lineEdit.setObjectName("filename_lineEdit")
        self.gridLayout_5.addWidget(self.filename_lineEdit, 7, 1, 1, 1)
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setObjectName("filename_label")
        self.gridLayout_5.addWidget(self.filename_label, 7, 0, 1, 1)
        self.browse_centroidFile_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.browse_centroidFile_pushButton.setObjectName("browse_centroidFile_pushButton")
        self.gridLayout_5.addWidget(self.browse_centroidFile_pushButton, 8, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.imageContainerLayout = QtWidgets.QGridLayout()
        self.imageContainerLayout.setObjectName("imageContainerLayout")
        self.gridLayout.addLayout(self.imageContainerLayout, 0, 0, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 5)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoAlign"))
        self.centerBeam_pushButton.setText(_translate("MainWindow", "Center Beam"))
        self.centerBeamSingle_pushButton.setText(_translate("MainWindow", "Center Beam Single Iteration"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.eraseLearned_pushButton.setText(_translate("MainWindow", "Erase Learned Data"))
        self.apply_filter_checkBox.setText(_translate("MainWindow", "Apply filter"))
        self.filter_mode_comboBox.setItemText(0, _translate("MainWindow", "red rgb"))
        self.filter_mode_comboBox.setItemText(1, _translate("MainWindow", "green rgb"))
        self.filter_mode_comboBox.setItemText(2, _translate("MainWindow", "blue rgb"))
        self.filter_mode_comboBox.setItemText(3, _translate("MainWindow", "red hsv"))
        self.filter_mode_comboBox.setItemText(4, _translate("MainWindow", "green hsv"))
        self.filter_mode_comboBox.setItemText(5, _translate("MainWindow", "blue hsv"))
        self.show_mask_checkBox.setText(_translate("MainWindow", "Show mask"))
        self.get_centroid_checkBox.setText(_translate("MainWindow", "Get centroid"))
        self.centroid_x_label.setText(_translate("MainWindow", "x : "))
        self.centroid_y_label.setText(_translate("MainWindow", "y : "))
        self.save_centroid_checkBox.setText(_translate("MainWindow", "Save centroid locations"))
        self.filename_label.setText(_translate("MainWindow", "Filename"))
        self.browse_centroidFile_pushButton.setText(_translate("MainWindow", "Browse"))

